/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Board: () => import('#controllers/board_controller'),
  Connect: () => import('#controllers/connect_controller'),
  Labels: () => import('#controllers/labels_controller'),
  Mcp: () => import('#controllers/mcp_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Oauth: () => import('#controllers/oauth_controller'),
  Session: () => import('#controllers/session_controller'),
}
